# Generated by Django 6.0.7 on 2026-10-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("desc", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SMARTPHONES", "Smartphones"),
                            ("CHARGERS", "Chargers"),
                            ("BACKCOVER", "Backcover"),
                        ],
                        max_length=225,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="products.tag")),
            ],
        ),
    ]
