# Generated by Django 6.0.7 on 2026-10-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AddField(
            model_name="products",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
